#!/bin/bash
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

if [ -x "$(command -v feh)" ]; then
  feh --bg-scale $SCRIPTPATH/leftwm/down.jpg
fi

echo "UnloadTheme" > $XDG_RUNTIME_DIR/leftwm/command-0.pipe

pkill copyq
pkill flameshot
pkill dunst
pkill polybar
pkill picom
pkill sxhkd
pkill nm-applet
pkill streamdeck
