#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# Set Wallpaper
feh --bg-scale $SCRIPTPATH/backgrounds/ign_unsplash1.png
#feh --bg-scale --randomize "$SCRIPTPATH/backgrounds/*"
wal --theme base16-nord
# keybindings daemon
sxhkd -c  $SCRIPTPATH/sxhkdrc &

# Start Network Manager Applet
nm-applet &

# Boot picom or compton if it exists
picom --config "$SCRIPTPATH"/picom.conf &> /dev/null &

#Set the theme.toml config
echo "LoadTheme $SCRIPTPATH/theme.toml" > $XDG_RUNTIME_DIR/leftwm/commands.pipe

#Start Polybar
index=0
monitors=($(polybar -m | sed s/:.*//))
leftwm-state -q -n -t "$SCRIPTPATH"/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
do
  barname="mainbar$index"
  monitor=${monitors[index]} width=$(( width - 16 )) polybar -c "$SCRIPTPATH"/polybar.config $barname &> /dev/null &
  let index=index+1
done
