#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

if [ -f ~/display.sh ]; then
  ~/display.sh
fi

if [ -f ~/.fehbg ]; then
  ~/.fehbg
elif [ -x "$(command -v feh)" ]; then
  feh --bg-scale $SCRIPTPATH/backgrounds/ign_outer_space.png
fi

if [ -x "$(command -v wal)" ]; then
  wal --theme base16-nord
fi

if [ -x "$(command -v sxhkd)" ]; then
  sxhkd -c  $SCRIPTPATH/sxhkd/sxhkdrc &
fi

if [ -x "$(command -v nm-applet)" ]; then
  nm-applet &
fi

if [ -x "$(command -v copyq)" ]; then
  copyq &
fi

if [ -x "$(command -v flameshot)" ]; then
  flameshot &> /dev/null &
fi

if [ -x "$(command -v picom)" ]; then
  picom --config "$SCRIPTPATH"/picom/picom.conf &> /dev/null &
fi

if [ -x "$(command -v dunst)" ]; then
  dunst -config "$SCRIPTPATH"/dunst/dunstrc &> /dev/null &
fi

if [ -x "$(command -v streamdeck)" ]; then
  streamdeck --no-ui &> /dev/null &
fi

echo "LoadTheme $SCRIPTPATH/theme.toml" > $XDG_RUNTIME_DIR/leftwm/command-0.pipe

index=0
monitors=($(polybar -m | sed s/:.*//))
leftwm-state -q -n -t "$SCRIPTPATH"/leftwm/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
do
  barname="mainbar$index"
  monitor=${monitors[index]} width=$(( width - 16 )) polybar -c "$SCRIPTPATH"/polybar/polybar.config $barname &> /dev/null &
  let index=index+1
done
