modkey = "Mod4"
mousekey = "Mod4"
disable_tile_drag = true
disable_current_tag_swap = true
disable_window_snap = true
focus_behaviour = "Sloppy"
focus_new_windows = true
sloppy_mouse_follows_focus = true
# https://github.com/leftwm/leftwm/blob/main/leftwm-core/src/layouts/mod.rs#L21
layouts = ["MainAndVertStack", "MainAndDeck", "GridHorizontal", "Monocle"]
layout_mode = "Tag"
tags = ["", "", "阮", "輸", "﬐", "拾"]
workspaces = [
    { y = 0, x = 0, height = 1440, width = 2560 },
    { y = 0, x = 2560, height = 1440, width = 2560 },
]
window_rules = [
    {window_class = "code-oss", spawn_on_tag = 1},
    {window_class = "emacs", spawn_on_tag = 1},
    {window_class = "spotify", spawn_on_tag = 3},
    {window_class = "freetube", spawn_on_tag = 4},
    {window_class = "discord", spawn_on_tag = 5},
    {window_class = "lxpolkit", spawn_floating = true}
]
scratchpad = [
    {name = "MainTerminal", value = "alacritty"},
    {name = "Notepad", value="marktext"},
]
# https://github.com/leftwm/leftwm/blob/main/leftwm-core/src/utils/xkeysym_lookup.rs#L46
keybind = [
    {command = "IncreaseMainWidth", value = "3", modifier = ["Control", "Shift"], key = "Right"},
    {command = "DecreaseMainWidth", value = "3", modifier = ["Control", "Shift"], key = "Left"},
]
